FROM java:8-jdk
RUN mkdir /app
WORKDIR /app
COPY build/libs/eureka-server.jar /app
EXPOSE 8761
CMD ["--spring.profiles.active=docker"]
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/eureka-server.jar"]
